# Generated by Django 6.1 on 2026-08-22 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'Quiz', 'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AlterModelOptions(
            name='quizquestion',
            options={'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
    ]
